version: '2.1'

services:

  company-shell:
    build:
      context: .
      dockerfile: ./shell/Dockerfile
    image: company-shell
    container_name: compan-shell
    volumes:
      - .:/project/sawtooth-supply
    command: |
      bash -c "
        protogen
        tail -f /dev/null"
    networks:
      - vchain_vChain
  company-tp-0:
    build:
        context: .
        dockerfile: ./processor/Dockerfile
    image: company-tp
    container_name: company-tp-0
    volumes:
      - '.:/project/sawtooth-supply'
    depends_on:
      - company-shell
    command: |
      bash -c "
        sleep 1
        tp -v -C tcp://validator-0:4004"
    networks:
      - vchain_vChain
  company-tp-1:
    build:
        context: .
        dockerfile: ./processor/Dockerfile
    image: company-tp
    container_name: company-tp-1
    volumes:
      - '.:/project/sawtooth-supply'
    depends_on:
      - company-shell
    command: |
      bash -c "
        sleep 1
        tp -v -C tcp://validator-1:4004"
    networks:
      - vchain_vChain
  company-tp-2:
    build:
      context: .
      dockerfile: ./processor/Dockerfile
    image: company-tp
    container_name: company-tp-2
    volumes:
      - '.:/project/sawtooth-supply'
    depends_on:
      - company-shell
    command: |
      bash -c "
        sleep 1
        tp -v -C tcp://validator-2:4004"
    networks:
      - vchain_vChain
  company-tp-3:
    build:
        context: .
        dockerfile: ./processor/Dockerfile
    image: company-tp
    container_name: company-tp-3
    volumes:
      - '.:/project/sawtooth-supply'
    depends_on:
      - company-shell
    command: |
      bash -c "
        sleep 1
        tp -v -C tcp://validator-3:4004"
    networks:
      - vchain_vChain
  company-tp-4:
    build:
        context: .
        dockerfile: ./processor/Dockerfile
    image: company-tp
    container_name: company-tp-4
    volumes:
      - '.:/project/sawtooth-supply'
    depends_on:
      - company-shell
    command: |
      bash -c "
        sleep 1
        tp -v -C tcp://validator-4:4004"
    networks:
      - vchain_vChain
  company-rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
    image: company-rest-api
    container_name: company-rest-api
    volumes:
      - .:/project/sawtooth-supply
    ports:
      - '8096:8096'
    depends_on:
      - company-shell
    command: |
      bash -c "
        rest-api \
          -B company-rest-api:8096 \
          -C validator-0:4004\
          -vv"
    networks:
      - vchain_vChain
networks:
  vchain_vChain:
    external: true

