# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/company.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/company.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16protobuf/company.proto\"\x86\x01\n\x07\x43ompany\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12 \n\x07updates\x18\x03 \x03(\x0b\x32\x0f.Company.Update\x1a?\n\x06Update\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x11\n\testablish\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\"-\n\x10\x43ompanyContainer\x12\x19\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x08.Companyb\x06proto3'
)




_COMPANY_UPDATE = _descriptor.Descriptor(
  name='Update',
  full_name='Company.Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Company.Update.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='establish', full_name='Company.Update.establish', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='Company.Update.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=161,
)

_COMPANY = _descriptor.Descriptor(
  name='Company',
  full_name='Company',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Company.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Company.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updates', full_name='Company.updates', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COMPANY_UPDATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=161,
)


_COMPANYCONTAINER = _descriptor.Descriptor(
  name='CompanyContainer',
  full_name='CompanyContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='CompanyContainer.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=208,
)

_COMPANY_UPDATE.containing_type = _COMPANY
_COMPANY.fields_by_name['updates'].message_type = _COMPANY_UPDATE
_COMPANYCONTAINER.fields_by_name['entries'].message_type = _COMPANY
DESCRIPTOR.message_types_by_name['Company'] = _COMPANY
DESCRIPTOR.message_types_by_name['CompanyContainer'] = _COMPANYCONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Company = _reflection.GeneratedProtocolMessageType('Company', (_message.Message,), {

  'Update' : _reflection.GeneratedProtocolMessageType('Update', (_message.Message,), {
    'DESCRIPTOR' : _COMPANY_UPDATE,
    '__module__' : 'protobuf.company_pb2'
    # @@protoc_insertion_point(class_scope:Company.Update)
    })
  ,
  'DESCRIPTOR' : _COMPANY,
  '__module__' : 'protobuf.company_pb2'
  # @@protoc_insertion_point(class_scope:Company)
  })
_sym_db.RegisterMessage(Company)
_sym_db.RegisterMessage(Company.Update)

CompanyContainer = _reflection.GeneratedProtocolMessageType('CompanyContainer', (_message.Message,), {
  'DESCRIPTOR' : _COMPANYCONTAINER,
  '__module__' : 'protobuf.company_pb2'
  # @@protoc_insertion_point(class_scope:CompanyContainer)
  })
_sym_db.RegisterMessage(CompanyContainer)


# @@protoc_insertion_point(module_scope)
